export enum actionTypes {
  SEARCH_INPUT_VALUE="SEARCH_INPUT_VALUE",
  GET_YOUTUBE_SEARCH_RESULT ="GET_YOUTUBE_SEARCH_RESULT",
  SET_SEARCH_TYPE="SEARCH_TYPE",
  SET_PUBLISH_AFTER="SET_PUBLISH_AFTER",
  GET_YOUTUBE_VIDEO_DETAILS="GET_YOUTUBE_VIDEO_DETAILS",
  GET_YOUTUBE_VIDEO_STATICS="GET_YOUTUBE_VIDEO_STATICS",
  GET_YOUTUBE_CHANNEL_DETAILS="GET_YOUTUBE_CHANNEL_DETAILS",
  Is_LOADING = "Is_LOADING",
  LOADING_IS_FINISHED="LOADING_IS_FINISHED"

}
